//const bill = 275;
//const tip = bill <= 300 && bill >= 50 ? bill * .15 :
//bill * 0.2;
console.log('The bill was ${bill}, the tip was ${tip}, and the total value ${bill + tip}');
console.log('The bill was ${275}, the tip was ${41.25}, and the total value ${316.25}');
bill <= 300 && bill >= 50

const bill = 40;
const tip = bill <= 300 && bill >= 50 ? bill * .15 :
    bill * 0.2;
console.log('The bill was ${40}, th tip was ${8}, and the total value ${40 + 8}');